services:
  postgres:
    image: postgres:15
    container_name: postgres-dmx
    environment:
      POSTGRES_DB: dmx_database
      POSTGRES_USER: dmx_user
      POSTGRES_PASSWORD: dmx_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
